before:
  hooks:
  - go mod download

builds:
- main: ./cmd/kubectl-graph
  binary: kubectl-graph
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- format_overrides:
  - goos: windows
    format: zip
